### PR TITLE
New Search Field

### PR DESCRIPTION
**Pull request by taojun545**
Add new search field at the top, and it allow user to search Name/Title/Description.

### CODE REVIEW

**Comment by talllguy** [comment]
This looks cool, nice work!

It is a tiny bit slow though. Maybe we can reduce the [searched fields](https://github.com/kcigeospatial/tmdl-grass-swale-map/pull/29/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR193) to just the name, as (at least in this project) that is the one with the data. I also might consider replacing <kbd>_</kbd> with <kbd>SPACE</kbd> in the data to help it parse those long names. What do you think?

search

CC @cmolivi

**Comment by talllguy** [comment]
:book: Reference #23

**Comment by taojun545** [comment]
I am thinking does it need a button to click instead of auto-filter? Like top right menu, click to filter.

**Comment by talllguy** [comment]
Awesome work @taojun545 it seems faster now.

**Pull request merged**
