### PR TITLE
Add logic for show/hide Waze Button

### PR DESCRIPTION
**Pull request by taojun545**
Only show in iOS device.

### CODE REVIEW

**Comment by talllguy** [comment]
Tested on PC and it doesn't show the button.

**Comment by talllguy** [comment]
Would this also hide the button on an Android tablet / phone?

**Comment by taojun545** [comment]
Yes, it is also hidden on Android device, since the button url is only for iOS API

**Comment by talllguy** [comment]
Got it, reading a bit it doesn't look like that URL is supported on Android. Is there an android version I wonder?

**Comment by taojun545** [comment]
I just tested the iOS URL in Android device, it works. So I changed the code to show the button in both iOS and Android devices.

**Comment by talllguy** [comment]
Looks great! I tried it on iOS and it shows the button. I'd say this is safe to PR.

**Pull request merged**
